# Generated by Django 3.2.5 on 2021-09-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_english', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
    ]
